@include('crm.categories.forms._input',[
'label'=>'имя',
'name'=>'name',
'type'=>'string',
'value'=>isset($products)?$products->getName():'',
])@include('crm.categories.forms._input',[
'label'=>'цена ',
'name'=>'price',
'type'=>'string',
'value'=>isset($products)?$products->getPrice():'',
])
@include('crm.categories.forms._input',[
'label'=>'Изображение',
'name'=>'image_url',
'type'=>'file',
'value'=>isset($products)?$products->getImageUrl():'',
])
@include('crm.categories.forms._input',[
'label'=>'Текст',
'name'=>'description',
'type'=>'trix',
'value'=>isset($products)?$products->getDescription():'',

])
{{--@include('crm.categories.forms._input',[--}}
{{--'label'=>'категория',--}}
{{--'name'=>'category_id',--}}
{{--'type'=>'select',--}}
{{--'value'=>isset($products)?$products->getCategory_id():'',--}}
{{--])--}}
