@include('forms._input',[
'label'=>'имя',
'name'=>'name',
'type'=>'string',
'value'=>isset($products)?$products->getName():'',
])@include('forms._input',[
'label'=>'цена ',
'name'=>'price',
'type'=>'string',
'value'=>isset($products)?$products->getPrice():'',
])
@include('forms._input',[
'label'=>'Изображение',
'name'=>'image_url',
'type'=>'file',
'value'=>isset($products)?$products->getImageUrl():'',
])
@include('forms._input',[
'label'=>'Текст',
'name'=>'description',
'type'=>'trix',
'value'=>isset($news)?$news->getDescription():'',

])
@include('forms._input',[
'label'=>'категория',
'name'=>'category_id',
'type'=>'string',
'value'=>isset($news)?$news->getCategory_id():'',
])
