@include('forms._input',[
'label'=>'имя',
'name'=>'name',
'type'=>'string',
'value'=>isset($news)?$news->getNewsName():'',
])
@include('forms._input',[
'label'=>'Изображение',
'name'=>'image_url',
'type'=>'file',
'value'=>isset($news)?$news->getImageUrl():'',
])
@include('forms._input',[
'label'=>'Текст',
'name'=>'discription',
'type'=>'trix',
'value'=>isset($news)?$news->getDicription():'',

])
@include('forms._input',[
'label'=>'номер',
'name'=>'ordering',
'type'=>'string',
'value'=>isset($news)?$news->getOrdering():'',
])
